### ISSUE TITLE
Sphinx not finding journal_info module

### ISSUE THREAD

**Issue by cmsquared** [zingale/pyjournal2#1]
I'm not sure what version of Sphinx you are using, but on 1.8.1, it appears to go into the source directory before running any scripts.  The journal_info.py file is generated one directory up, at the root of the repo that stores journal contents.  Journal was setup as follows:

```bash
python3 setup.py install
pyjournal.py init notes cmalone Documents/journals
pyjournal.py entry diffusion
pyjournal.py show
```

Going to the directory (Documents/journals/journal-notes) and directly running the Makefile results in the same error.  

Did I set something up incorrectly?

**Comment by zingale** [comment]
I don't think you did anything wrong.  My `journal_info.py` is in the top-level directory, where the `Makefile` is too.  It seemed to me that since `make` is run there, the `conf.py` uses that directory as the starting point for finding modules.

Does it build if you put `journal_info.py` in `source/`?

**Comment by cmsquared** [comment]
Yes.  I was just not sure how it was working for you.  Or which solution you preferred: mucking with config.py to change `sys.path` to include the correct directory, or just putting that file in the source directory.

**Comment by zingale** [comment]
I don't know why it works for me (but it does :/ )
interestingly, it doesn't work for me if `journal_info.py` is in the `source/` directory...

so something about our systems are different.  Maybe my sphinx-build is defaulting to python2?

**Comment by zingale** [comment]
it looks like I am using sphinx-build 1.8.1 with python 3.6.6

**Comment by cmsquared** [comment]
I'm on same sphinx but 3.6.4 python.  This shoudn't be the issue.  I'm on a Mac, but that, too, shouldn't be an issue like this...  I'll keep looking

**Comment by cmsquared** [comment]
Just to be certain, could you locally modify your `config.py` in your journal directory to print out `sys.path` to make sure that the top-level directory isn't somehow in there?

I've traced through what Sphinx does and on line 366 of my installed sphinx/config.py (which reads the user-supplied config.py), it is clearly `cd`'ing into `source` before parsing the file that lives in there.

If it is not that, then maybe it is a 2.x vs 3.x thing?  Ultimately the journal's config.py gets called by `six.exec_`, which is naturally a place where we could diverge if your `sphinx-build` is using 2.x.  I checked that mine is using the 3.6.4 version of python.

**Comment by cmsquared** [comment]
Ok, something else might be afoot.  I was mistaken before -- if I put the journal_info module into source, the build still fails to find the module.  Something must be screwy with my system setup...

In fact, the source directory (nor the top-level directory) does not show up in `sys.path` when printed from source/config.py.  What _does_ work is to uncomment the boilerplate stuff that adds `.` to `sys.path`, and copying the journal.py file over to source.

**Comment by zingale** [comment]
maybe the issue is that `.` seems to be in my `sys.path`, but I'm guessing not in yours.
